Bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/about'
  get 'homes/about'
  get 'home/about'
  get 'users/top'
  root 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :index, :create, :edit, :new, :update]
  resources :books, only: [:show, :index, :create, :edit, :new, :update, :destroy]
end

Bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, :body, presence: true
	validates :body, length: {maximum:200}
end

Bookers2/app/models/home.rb
class Home < ApplicationRecord
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum:50}
  validates :email, presence: true
end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!, :except=>[:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(resource)
	end


	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :ensure_user, :only=>[:edit, :update, :destroy]


	def ensure_user
		@book = Book.find(params[:id])
		if current_user.id != @book.user_id
			redirect_to books_path
			end
		end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			flash[:mess] = "edit successfully"
			redirect_to book_path(@book)
		else
			flash[:mess] = "edit error"
			redirect_to books_path
		end
	end

	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end

	def show
		@book_detail = Book.find(params[:id])
		@book = Book.new
		@user = @book_detail.user
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:mess] = "edit successfully"
		else
			flash[:mess] = "edit error"
		end
		redirect_to book_path(@book)
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
end

Bookers2/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def about
	end
end

Bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def about
	end
end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_user, :only=>[:edit, :update]

  def ensure_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user)
    end
  end


  def index
	@users = User.all
  @user = current_user
  @book = Book.new
  end

  def top
  end

  def about
  end

  def show
  	@user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:mess] = "edit successfully"
    else
      flash[:mess] = "edit error"
    end
    redirect_to user_path(@user)
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to user_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

Bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers2/app/helpers/books_helper.rb
module BooksHelper
end

Bookers2/app/helpers/home_helper.rb
module HomeHelper
end

Bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

Bookers2/app/helpers/users_helper.rb
module UsersHelper
end

Bookers2/app/views/books/edit.html.erb
<%= render 'users/header' %>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
				<div class="form-group">
					<%= f.label "Title" %>
					<br>
					<%= f.text_field :title %>
				</div>
			<div class="form-group">
				<%= f.label "Body" %>
				<br>
				<%= f.text_area :body %>
			</div>
			<%= f.submit "Update Book" %>
			<% end %>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/books/index.html.erb
<%= render 'users/header' %>
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/side-bar', book: @book %>
		</div>
		<div class="col-lg-9">
			<h1>Books</h1>
			<table class="table table-striped">
				<tr>
					<th class="list-title"></th>
					<th class="list-title">Title</th>
					<th class="list-title">Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr>
						<th class="list-text">
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
							<% end %>
						</th>
						<th class="list-text">
							<%= link_to  book_path(book) do %>
								<%= book.title %>
							<% end %>
						</th>
						<th class="list-text"><%= book.body %></th>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/books/show.html.erb
<% if flash[:mess] %>
	<p><%= flash[:mess] %></p>
<% end %>

<%= render 'users/header', user: @book_detail.user %>
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/side-bar' %>
		</div>
		<div class="col-lg-9">
			<h1>Book detail</h1>
			<table class="table table-striped">
				<tr>
					<th class="list-text">
						<%= link_to user_path(@book_detail.user) do %>
						<%= attachment_image_tag @book_detail.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
						<br>
						<%= @book_detail.user.name %>
						<% end %>
					</th>
					<th class="list-text">
						<%= link_to  book_path(@book_detail) do %>
						<%= @book_detail.title %>
						<% end %>
					</th>
					<th class="list-text"><%= @book_detail.body %></th>
					<% if @book_detail.user == current_user %>
					<th class="list-edit">
						<%= link_to edit_book_path do %>
						<button type="button" class="btn btn-success">Edit</button>
						<% end %>
					</th>
					<th class="list-destroy">
						<%= link_to book_path(@book_detail), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
						<button type="button" class="btn btn-danger">Destroy</button>
						<% end %>
					</th>
					<% end %>
				</tr>
			</table>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/home/about.html.erb
<%= render 'users/header' %>
<div class="container">
	<h1>Weicome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/homes/about.html.erb
<%= render 'users/header' %>
<div class="container">
<h1>Weicome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>

Bookers2/app/views/layouts/_mess.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

Bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/mess' %>
    <%= yield %>
  </body>
</html>

Bookers2/app/views/users/_copyright.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-right">
			<p>CopyRight Infratop.inc</p>
		</div>
	</div>
</div>

Bookers2/app/views/users/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class="container">
		<div class="row">
			<div class="navbar-header">
				<h3 class="navbar-text">Bookers</h3>
			</div>
			<div class="row navbar-right">
				<div class="collapse navbar-collapse" id="nav-menu">
					<ul class="nav navbar-nav navbar-right">
						<% if user_signed_in? %>
							<li>
								<%= link_to  user_path(current_user) do %>
								<i class="glyphicon glyphicon-home" aria-hidden="true"> Home</i>
								<% end %>
							</li>
							<li>
								<%= link_to  users_path do %>
								<i class="glyphicon glyphicon-user" aria-hidden="true"> User</i>
								<% end %>
							</li>
							<li>
								<%= link_to  books_path do %>
								<i class="glyphicon glyphicon-book" aria-hidden="true"> Book</i>
								<% end %>
							</li>
							<li>
								<%= link_to  destroy_user_session_path, method: :delete do %>
								<i class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</i>
								<% end %>
							</li>
						<% else %>
							<li>
								<a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
							</li>
							<li>
								<a href="/home/about"><span class="glyphicon glyphicon-link" aria-hidden="true"></span> About</a>
							</li>
							<li>
								<a href="/users/sign_up"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> sign up</a>
							</li>
							<li>
								<a href="/users/sign_in"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span> login</a>
							</li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</nav>

Bookers2/app/views/users/_side-bar.html.erb
<h1>User info</h1>
<th class="list-text"><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></th>
<table class="table table-striped">
	<tr>
		<th class="side-title">name</th>
		<th class="side-text"><%= @user.name %></th>
	</tr>
	<tr>
		<th class="side-title">introduction</th>
		<th class="side-text"><%= @user.introduction %></th>
	</tr>
</table>

<%= link_to edit_user_path(@user) do %>
	<button type="button" class="btn btn-outline-secondary btn-block"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
<% end %>

<h1>New book</h1>
<%= form_for(@book) do |f| %>
	<div class="form-group">
		<%= f.label "Title" %>
		<br>
		<%= f.text_field :title %>
	</div>
	<div class="form-group">
		<%= f.label "Opinion" %>
		<br>
		<%= f.text_area :body %>
	</div>
	<div class="form-group">
		<%= f.submit "Create Book", class:"btn btn-primary btn-block"%>
	</div>
<% end %>

Bookers2/app/views/users/about.html.erb
<%= render 'users/header' %>
<div class="container">
	<h1>Weicome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!</h1>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/users/edit.html.erb
<%= render 'users/header' %>
<div class="container">
	<h1>User info</h1>
	<%= form_for(@user) do |f| %>
		<div class="form-group">
			<%= f.label "Name" %>
			<%= f.text_field :name %>
		</div>
		<div class="form-group">
			<%= f.label 'image' %>
			<%= f.attachment_field :profile_image %>
		</div>
		<div class="form-group">
			<%= f.label "introduction" %>
			<%= f.text_area :introduction %>
		</div>
		<%= f.submit "Update User" %>
	<% end %>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/users/index.html.erb
<% if flash[:mess] %>
	<p><%= flash[:mess] %></p>
<% end %>

<%= render 'users/header', user: @user %>
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/side-bar', book: @book %>
		</div>
		<div class="col-lg-9">
			<h1>Users</h1>
			<table class="table table-striped">
				<tr>
					<th class="list-title">image</th>
					<th class="list-title">name</th>
					<th class="list-title"></th>
				</tr>
				<% @users.each do |user| %>
					<tr>
						<th class="list-text"><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></th>
						<th class="list-text"><%= user.name %></th>
						<th class="list-text"><%= link_to "Show", user_path(user) %></th>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/users/show.html.erb
<%= render 'users/header'%>
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<%= render 'users/side-bar', book: @book %>
		</div>
		<div class="col-lg-9">
			<h1>Books</h1>
			<table class="table table-striped">
				<tr>
					<th class="list-title"></th>
					<th class="list-title">Title</th>
					<th class="list-title">Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr>
						<th class="list-text">
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
							<% end %>
						</th>
						<th class="list-text">
							<%= link_to  book_path(book) do %>
								<%= book.title %>
							<% end %>
						</th>
						<th class="list-text"><%= book.body %></th>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>

Bookers2/app/views/users/top.html.erb
<%= render 'users/header' %>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers!!</h1>
			<div class="form-group">
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers,</p>
			<p>you can share and exchange your opinions, inpressions, and emotions</p>
			<p>about varioius books!</p>
			</div>
			<%= link_to new_user_session_path do %>
			<button type="button" class="btn btn-primary btn-block">Log in</button>
			<% end %>
			<%= link_to new_user_registration_path do %>
			<button type="button" class="btn btn-success btn-block">Sign up</button>
			<% end %>
		</div>
	</div>
</div>
<%= render 'users/copyright' %>